<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="about.aspx.vb" Inherits="about" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<p>Fußball-Club Bayern München, commonly known as FC Bayern München, FC Bayern Munich, or FC Bayern, is a German sports club based in Munich, Bavaria. It is best known for its professional football team, which plays in the Bundesliga, the top tier of the German football league system, and is the most successful club in German football history, having won a record 23 national titles and 16 national cups.</p>
<br /><p>FC Bayern was founded in 1900 by eleven football players led by Franz John. Although Bayern won its first national championship in 1932, the club was not selected for the Bundesliga at its inception in 1963. The club had its period of greatest success in the middle of the 1970s when, under the leadership of Franz Beckenbauer, it won the European Cup three times in a row (1974–76). Overall Bayern has reached ten European Cup/UEFA Champions League finals, most recently winning their fifth in 2013 as part of a continental treble. Bayern has also won one UEFA Cup, one European Cup Winners' Cup, one UEFA Super Cup and two Intercontinental Cups, making it one of the most successful European clubs internationally. Since the formation of the Bundesliga, Bayern has been the dominant club in German football with 22 titles and has won five of the last ten titles. They have traditional local rivalries with TSV 1860 München and 1. FC Nuremberg, as well as a contemporary rivalry with Borussia Dortmund.</p>
<br /><p>Since the beginning of the 2005–06 season Bayern has played its home games at the Allianz Arena. Previously the team had played at Munich's Olympic Stadium for 33 years. The team colours are red and white, and the team crest shows the white and blue flag of Bavaria. In terms of revenue, Bayern Munich is the biggest sports club in Germany and the fourth biggest football club in the world, generating €368.4 million in 2012. Bayern is a membership-based club with more than 200,000 members. There are also 3,202 officially-registered fan clubs with 231,197 members. The club has other departments for chess, handball, basketball, gymnastics, bowling, table tennis, referees, and senior football with more than 1,100 active members.</p>

</asp:Content>

